use crate::*;

#[derive(Debug)]
pub(crate) struct SeedTask {
    pub(crate) id: Uuid,
    pub(crate) key: &'static str,
    pub(crate) title: &'static str,
    pub(crate) title_en: &'static str,
    pub(crate) description: &'static str,
    pub(crate) description_en: &'static str,
    pub(crate) tag: &'static str,
    pub(crate) tag_color: &'static str,
    pub(crate) priority: Priority,
    pub(crate) status_id: Uuid,
    // Days relative to "today" so the demo always shows live-looking data.
    pub(crate) start_offset: i64,
    pub(crate) due_offset: i64,
    pub(crate) phase: &'static str,
    pub(crate) assignees: &'static [&'static str],
    pub(crate) subtasks: &'static [(&'static str, &'static str, bool)],
}

pub(crate) fn seed_tasks(status_ids: [Uuid; 4]) -> Result<Vec<SeedTask>, AppError> {
    Ok(vec![
        SeedTask {
            id: fixed_uuid("30000000-0000-4000-8000-000000000104")?,
            key: "KWB-104",
            title: "Mängelaufnahme koordinieren",
            title_en: "Coordinate defect walk-through",
            description: "Begehung für die Wohnungseingänge A-C koordinieren, Fotos sichern und Nachfristen mit den Gewerken abstimmen.",
            description_en: "Coordinate the walk-through for entrances A-C, capture photos and align remediation deadlines with the trades.",
            tag: "Ausführung",
            tag_color: "accent",
            priority: Priority::Urgent,
            status_id: status_ids[1],
            start_offset: -2,
            due_offset: 0,
            phase: "ausfuehrung",
            assignees: &["TL", "JS"],
            subtasks: &[
                ("Begehungstermin bestätigen", "Confirm walk-through appointment", true),
                ("Fotodokumentation anlegen", "Create photo documentation", true),
                ("Mängelliste mit Gewerken abstimmen", "Align defect list with trades", true),
                ("Nachfrist für offene Punkte setzen", "Set deadline for open items", true),
                ("Rückmeldung an Bauleitung senden", "Send update to site management", false),
                ("Abnahme-Nachtermin planen", "Plan follow-up handover", false),
            ],
        },
        SeedTask {
            id: fixed_uuid("30000000-0000-4000-8000-000000000107")?,
            key: "KWB-107",
            title: "Terminplan aktualisieren",
            title_en: "Update construction schedule",
            description: "Bauzeitenplan mit neuen Lieferterminen, Pufferzeiten und Abhängigkeiten für Ausbau und Fassade aktualisieren.",
            description_en: "Update the construction schedule with new delivery dates, buffers and dependencies for interiors and facade work.",
            tag: "Planung",
            tag_color: "good",
            priority: Priority::High,
            status_id: status_ids[1],
            start_offset: -1,
            due_offset: 2,
            phase: "planung",
            assignees: &["MR", "AK"],
            subtasks: &[
                ("Liefertermine einarbeiten", "Add delivery dates", true),
                ("Kritischen Pfad prüfen", "Review critical path", true),
                ("Puffer für Fassade setzen", "Set facade buffer", false),
                ("Plan an Team verteilen", "Share schedule with team", false),
            ],
        },
        SeedTask {
            id: fixed_uuid("30000000-0000-4000-8000-000000000101")?,
            key: "KWB-101",
            title: "Freigabe Brandschutzkonzept",
            title_en: "Approve fire-safety concept",
            description: "Brandschutznachweise prüfen, Rückfragen klären und die Freigabe im Projektordner ablegen.",
            description_en: "Review fire-safety evidence, resolve questions and file the approval in the project folder.",
            tag: "Planung",
            tag_color: "accent",
            priority: Priority::High,
            status_id: status_ids[3],
            start_offset: -8,
            due_offset: -3,
            phase: "planung",
            assignees: &["JS"],
            subtasks: &[("Nachweise prüfen", "Review evidence", true), ("Rückfragen klären", "Resolve questions", true), ("Freigabe ablegen", "File approval", true)],
        },
        SeedTask {
            id: fixed_uuid("30000000-0000-4000-8000-000000000102")?,
            key: "KWB-102",
            title: "Bemusterung Wohnungen",
            title_en: "Apartment sample selection",
            description: "Materialvarianten für Boden, Bad und Türen final abstimmen und im Musterkatalog dokumentieren.",
            description_en: "Finalize material variants for flooring, bathrooms and doors and document them in the sample catalog.",
            tag: "Bemusterung",
            tag_color: "cool",
            priority: Priority::Medium,
            status_id: status_ids[3],
            start_offset: -10,
            due_offset: -6,
            phase: "planung",
            assignees: &["AK"],
            subtasks: &[("Bodenbelag festlegen", "Select flooring", true), ("Badserie freigeben", "Approve bathroom series", true), ("Türliste exportieren", "Export door list", true)],
        },
        SeedTask {
            id: fixed_uuid("30000000-0000-4000-8000-000000000103")?,
            key: "KWB-103",
            title: "Mieterinformation vorbereiten",
            title_en: "Prepare tenant communication",
            description: "Aushang, Terminfenster und Ansprechpartner für die Modernisierungsarbeiten abstimmen.",
            description_en: "Align notices, appointment windows and contacts for the modernization work.",
            tag: "Kommunikation",
            tag_color: "cool",
            priority: Priority::Medium,
            status_id: status_ids[1],
            start_offset: -3,
            due_offset: 1,
            phase: "planung",
            assignees: &["AK", "MR"],
            subtasks: &[("Aushang entwerfen", "Draft notice", true), ("Terminfenster prüfen", "Check appointment windows", false), ("Ansprechpartner ergänzen", "Add contacts", false), ("Freigabe Verwaltung", "Administration approval", false), ("Verteilung planen", "Plan distribution", false)],
        },
        SeedTask {
            id: fixed_uuid("30000000-0000-4000-8000-000000000105")?,
            key: "KWB-105",
            title: "Gewerkefreigabe dokumentieren",
            title_en: "Document trade approvals",
            description: "Freigaben für Elektro, Sanitär und Trockenbau inklusive Prüfnachweise im Projektraum ablegen.",
            description_en: "File approvals for electrical, plumbing and drywall work, including verification documents, in the project room.",
            tag: "Vergabe",
            tag_color: "ink",
            priority: Priority::Low,
            status_id: status_ids[0],
            start_offset: 1,
            due_offset: 3,
            phase: "vergabe",
            assignees: &["JS"],
            subtasks: &[("Elektrofreigabe ablegen", "File electrical approval", false), ("Sanitärfreigabe ablegen", "File plumbing approval", false), ("Trockenbau-Nachweis ergänzen", "Add drywall evidence", false)],
        },
        SeedTask {
            id: fixed_uuid("30000000-0000-4000-8000-000000000106")?,
            key: "KWB-106",
            title: "Abnahmeprotokoll prüfen",
            title_en: "Review handover protocol",
            description: "Protokoll für Bauabschnitt A gegen Fotodokumentation, Restarbeiten und Unterschriften prüfen.",
            description_en: "Check the phase A handover protocol against photos, remaining work and signatures.",
            tag: "Abnahme",
            tag_color: "good",
            priority: Priority::High,
            status_id: status_ids[2],
            start_offset: -3,
            due_offset: -1,
            phase: "abnahme",
            assignees: &["MR"],
            subtasks: &[("Fotos abgleichen", "Compare photos", true), ("Unterschriften prüfen", "Check signatures", true), ("Restarbeiten markieren", "Mark remaining work", false)],
        },
        SeedTask {
            id: fixed_uuid("30000000-0000-4000-8000-000000000108")?,
            key: "KWB-108",
            title: "Restarbeiten kontrollieren",
            title_en: "Check remaining work",
            description: "Offene Punkte aus der Abnahme in Treppenhaus und Keller prüfen und Status aktualisieren.",
            description_en: "Check open handover items in the stairwell and basement and update their status.",
            tag: "QA",
            tag_color: "cool",
            priority: Priority::Medium,
            status_id: status_ids[2],
            start_offset: 0,
            due_offset: 1,
            phase: "abnahme",
            assignees: &["SB"],
            subtasks: &[("Treppenhaus prüfen", "Check stairwell", true), ("Keller prüfen", "Check basement", true), ("Status im Protokoll setzen", "Update protocol status", false)],
        },
        SeedTask {
            id: fixed_uuid("30000000-0000-4000-8000-000000000109")?,
            key: "KWB-109",
            title: "Baustellenbericht erstellen",
            title_en: "Create site report",
            description: "Wochenbericht mit Wetter, Fortschritt, Risiken und Fotos für Eigentümer und Verwaltung erstellen.",
            description_en: "Create the weekly report with weather, progress, risks and photos for owners and administration.",
            tag: "Bericht",
            tag_color: "ink",
            priority: Priority::Low,
            status_id: status_ids[3],
            start_offset: -6,
            due_offset: -4,
            phase: "ausfuehrung",
            assignees: &["DK"],
            subtasks: &[("Fotoliste ergänzen", "Add photo list", true), ("Risiken aktualisieren", "Update risks", true)],
        },
        SeedTask {
            id: fixed_uuid("30000000-0000-4000-8000-000000000110")?,
            key: "KWB-110",
            title: "Bauabschnitt B vorbereiten",
            title_en: "Prepare construction phase B",
            description: "Baulogistik, Materialabruf, Sicherheitsunterweisung und Kommunikationsplan für Bauabschnitt B vorbereiten.",
            description_en: "Prepare site logistics, material call-offs, safety briefing and communication plan for construction phase B.",
            tag: "Meilenstein",
            tag_color: "accent",
            priority: Priority::Urgent,
            status_id: status_ids[0],
            start_offset: 4,
            due_offset: 7,
            phase: "ausfuehrung",
            assignees: &["AL", "JS"],
            subtasks: &[("Materialabruf prüfen", "Check material call-offs", false), ("Logistikfläche reservieren", "Reserve logistics area", false), ("Sicherheitsunterweisung planen", "Schedule safety briefing", false), ("Mieterinformation versenden", "Send tenant notice", false)],
        },
    ])
}

pub(crate) fn people_by_initial(initials: &str) -> Result<Uuid, AppError> {
    let id = match initials {
        "AL" => "20000000-0000-4000-8000-000000000001",
        "AK" => "20000000-0000-4000-8000-000000000002",
        "MR" => "20000000-0000-4000-8000-000000000003",
        "JS" => "20000000-0000-4000-8000-000000000004",
        "TL" => "20000000-0000-4000-8000-000000000005",
        "SB" => "20000000-0000-4000-8000-000000000006",
        "DK" => "20000000-0000-4000-8000-000000000007",
        _ => {
            return Err(AppError::BadRequest(format!(
                "unknown seed user {initials}"
            )))
        }
    };
    fixed_uuid(id)
}
